[package]
name = "pdao-logging"
version = "0.1.4"
edition = "2021"
rust-version = "1.77.2"
authors = ["kukabi <kutsal@helikon.io>"]

[dependencies]
env_logger = { workspace = true }
pdao-config = { path = "../pdao-config" }
log = { workspace = true }