[common]
recovery_retry_seconds = 5

[log]
pdao_level = "debug"
other_level = "warn"

[http]
request_timeout_seconds = 20

[postgres]
host = "127.0.0.1"
port = 5432
username = "pdao"
password = "pdao"
database_name = "pdao"
pool_max_connections = 64
connection_timeout_seconds = 5

[substrate]
connection_timeout_seconds = 15
request_timeout_seconds = 15
gov_proxy_seed_phrase = "seed"

[metrics]
host = "127.0.0.1"
referendum_importer_port = 11010
voter_port = 11011

[referendum_importer]
opensquare_space = "permanence"

[telegram]
api_id = "telegram_api_id"
api_hash = "telegram_api_hash"
api_token = "telegram_api_token"
chat_id = -145
bot_username = "@permanence_dao_bot"
bot_chat_thread_id = 15

[openai]
organization= "openai_organization"
project = "openai_project"
api_key = "openai_api_key"

[voter]
voting_admin_usernames = "usernames_separated_by_comma"
real_account_address = "address"
proxy_account_seed_phrase = "seed_phrase"
sleep_seconds = 1800
min_referendum_id = 1200
member_count = 10

[archive]
working_dir_path = "/path/to/working/dir"
python_bin_path = "/path/to/venv/bin/python3"
script_path = "/path/to/archive_topic.py"
temp_file_dir_path = "/path/to/temp/file/dir"