[package]
name = "pdao-telegram-client"
version = "0.1.4"
edition = "2021"
rust-version = "1.77.2"

[dependencies]
anyhow = { workspace = true }
frankenstein = { version = "0.37", default-features = false, features = ["async-http-client", "async-telegram-trait"] }
html-escape = "0.2.13"
pdao-config = { path = "../pdao-config" }
pdao-types = { path = "../pdao-types" }
log = { workspace = true }